# `grblas` new reprs!
## Come see the new HTML repr for `grblas` objects and expressions

In [1]:
from grblas import Vector, Matrix, binary, semiring

### Click on the output to show or hide the data

In [2]:
v = Vector.from_values([0, 2, 4], [0, 1, 2])
v

"v_0"          nvals  size  dtype
grblas.Vector      3     5  INT64
---------------------------------
  0 1  2 3  4
  0    1    2

### Give your own name to objects, and show truncated preview of large objects

In [3]:
Vector.from_values([0, 2 ** 53 - 1], [0, 1], name="v_huge")

"v_huge"       nvals              size  dtype
grblas.Vector      2  9007199254740992  INT64
---------------------------------------------
 0                1                2                3                 \
                0

 4                5                6                7                 \


 8                9                 ... 9007199254740982 9007199254740983  \
                                    ...

 9007199254740984 9007199254740985 9007199254740986 9007199254740987  \


 9007199254740988 9007199254740989 9007199254740990 9007199254740991
                                                                   1

### A Matrix and its transpose...

In [4]:
A = Matrix.from_values([1, 3, 1, 3], [0, 1, 2, 4], [0, 1, 2, 3])
A

"M_0"          nvals  nrows  ncols  dtype
grblas.Matrix      4      4      5  INT64
-----------------------------------------
   0  1  2 3  4
0
1  0     2
2
3     1       3

In [5]:
# This doesn't compute the transpose (do `A.T.new()` for that).
# Instead, `A.T` is used to set the appropriate transpose descriptor when used in an expression.
A.T

"M_0.T"                  nvals  nrows  ncols  dtype
grblas.TransposedMatrix      4      5      4  INT64
---------------------------------------------------
  0  1 2  3
0    0
1         1
2    2
3
4         3

### Masks...

In [6]:
A.S

"M_0.S"           nvals  nrows  ncols  dtype
StructuralMask
of grblas.Matrix      4      4      5  INT64
--------------------------------------------
   0  1  2 3  4
0
1  1     1
2
3     1       1

In [7]:
~A.V

"~M_0.V"               nvals  nrows  ncols  dtype
ComplementedValueMask
of grblas.Matrix           4      4      5  INT64
-------------------------------------------------
   0  1  2 3  4
0
1  1     0
2
3     0       0

### Delayed expressions...

In [8]:
A.mxv(v)

grblas.VectorExpression                      size  dtype
M_0.mxv(v_0, op=semiring.plus_times[INT64])     4  INT64

Do expr.new() or other << expr to calculate the expression.

In [9]:
A.mxm(A.T, semiring.min_plus)

grblas.MatrixExpression                      nrows  ncols  dtype
M_0.mxm(M_0.T, op=semiring.min_plus[INT64])      4      4  INT64

Do expr.new() or other << expr to calculate the expression.

In [10]:
v.apply(binary.times, right=10)

grblas.VectorExpression                   size  dtype
v_0.apply(binary.times[INT64], right=10)     5  INT64

Do expr.new() or other << expr to calculate the expression.

In [11]:
A.reduce_scalar()

grblas.ScalarExpression                dtype
M_0.reduce_scalar(monoid.plus[INT64])  INT64

Do expr.new() or other << expr to calculate the expression.